from django import forms

class ActuatorForms(forms.Form):
    height = forms.FloatField(widget=forms.NumberInput(attrs={ 'placeholder': 'H', 'class': 'constructor-inputs'}))
    force = forms.FloatField(widget=forms.NumberInput(attrs={ 'placeholder': 'F', 'class': 'constructor-inputs'}))
    stroke = forms.FloatField(widget=forms.NumberInput(attrs={ 'placeholder': 'L', 'class': 'constructor-inputs'}))
    minLen = forms.FloatField(widget=forms.NumberInput(attrs={ 'placeholder': 'Min length', 'class': 'constructor-inputs'}))
    angleSimul = forms.FloatField(widget=forms.NumberInput(attrs={ 'placeholder': 'Max Angle', 'class': 'constructor-inputs'}))
    direction = forms.IntegerField(widget=forms.NumberInput(attrs={ 'placeholder': 'Direction', 'class': 'constructor-inputs'}))
    airLoad = forms.FloatField(widget=forms.NumberInput(attrs={ 'placeholder': 'Air Load', 'class': 'constructor-inputs'}))
    weight = forms.FloatField(widget=forms.NumberInput(attrs={ 'placeholder': 'Weight', 'class': 'constructor-inputs'}))
    step = forms.FloatField(widget=forms.NumberInput(attrs={ 'placeholder': 'Step', 'class': 'constructor-inputs'}))
    numGraph = forms.IntegerField(widget=forms.NumberInput(attrs={ 'placeholder': 'Number of Graph', 'class': 'constructor-inputs'}))
    tol = forms.FloatField(widget=forms.NumberInput(attrs={ 'placeholder': 'Tolerance', 'class': 'search-inputs'}))
    limXA1 = forms.CharField(widget=forms.TextInput(attrs={ 'placeholder': 'limXA1', 'class': 'search-inputs'}))
    limYA1 = forms.CharField(widget=forms.TextInput(attrs={ 'placeholder': 'limYA1', 'class': 'search-inputs'}))
    stepA1 = forms.FloatField(widget=forms.NumberInput(attrs={ 'placeholder': 'StepA1', 'class': 'search-inputs'}))
    limXA2 = forms.CharField(widget=forms.TextInput(attrs={ 'placeholder': 'limXA2', 'class': 'search-inputs'}))
    limYA2 = forms.CharField(widget=forms.TextInput(attrs={ 'placeholder': 'limYA2', 'class': 'search-inputs'}))
    stepA2 = forms.FloatField(widget=forms.NumberInput(attrs={ 'placeholder': 'StepA2', 'class': 'search-inputs'}))
