# Generated by Django 3.2.9 on 2021-12-07 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActuatorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('height', models.FloatField()),
                ('force', models.FloatField()),
                ('stroke', models.FloatField()),
                ('minLen', models.FloatField()),
                ('angleSimul', models.FloatField()),
                ('direction', models.IntegerField()),
                ('airLoad', models.FloatField()),
                ('weight', models.FloatField()),
                ('step', models.FloatField()),
                ('numGraph', models.IntegerField()),
                ('tol', models.FloatField()),
                ('limXA1', models.CharField(max_length=20)),
                ('limYA1', models.CharField(max_length=20)),
                ('stepA1', models.FloatField()),
                ('limXA2', models.CharField(max_length=20)),
                ('limYA2', models.CharField(max_length=20)),
                ('stepA2', models.FloatField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'order_with_respect_to': 'user',
            },
        ),
    ]
